environment: "int"

image:
  tag: $ARGOCD_APP_REVISION

apiService:
  path: "/api"
  externalName: "traceability.int.demo.catena-x.net"
  port: 80

autoscaling:
  enabled: false

ingress:
  enabled: true
  className: "nginx"
  annotations:
  hosts:
    - host: "traceability-portal.int.demo.catena-x.net"
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - "traceability-portal.int.demo.catena-x.net"
      # Default secret for certificate creation already provided to your namespace
      secretName: tls-secret
