environment: "int"

image:
  tag: $ARGOCD_APP_REVISION

autoscaling:
  enabled: false

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  hosts:
    - host: "traceability-portal.int.demo.catena-x.net"
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - "traceability-portal.int.demo.catena-x.net"
      # Default secret for certificate creation already provided to your namespace
      secretName: tls-secret
