---
# Default values for traceability.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  ##
  ## Which traceability container image to use.
  ##
  repository: ghcr.io/catenax-ng/product-traceability-foss-backend
  pullPolicy: IfNotPresent
  ##
  ## Overrides the image tag whose default is the chart appVersion.
  ##
  tag: "0.0.2"

##
## Image pull secret to create to obtain the container image
## Note: 'imagePullSecret.dockerconfigjson' takes precedence if configured together with 'imagePullSecrets'
##
imagePullSecret:
  dockerconfigjson: ""

##
## Existing image pull secret to use to obtain the container image
##
imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  ##
  ## Specifies whether a service account should be created per release
  ##
  create: true
  ##
  ## Annotations to add to the service account
  ##
  annotations: {}
  ##
  ## The name of the service account to use.
  ## If not set and create is true, a name is generated using the fullname template
  ##
  name: ""

podAnnotations: {}

podSecurityContext: {}
# fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
# runAsUser: 1000

##
## Whether to enable kubernetes liveness-probes
##
livenessProbe:
  enabled: true

##
## Whether to enable kubernetes readiness-probes
##
readinessProbe:
  enabled: true

##
## Whether to enable kubernetes startup-probes
##
startupProbe:
  enabled: true

##
## Traceability Endpoints
##
traceability:
  endpoints:
    # Default api for client communications
    default:
      port: "9191"
      path: /api
      ingress: false

##
## Service to expose the running application on a set of Pods as a network service.
##
service:
  type: ClusterIP

##
## Ingress declaration to publicly expose the network service.
##
ingress:
  ##
  ## Set to true to enable ingress record generation
  ##
  enabled: false
  ##
  ## Defines the ingress class to use https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-class
  ##
  className: ""
  ##
  ## Enables TLS on the ingress resource
  ##
  tls: false

  ##
  ## Adds cert-manager annotations to the ingress
  ##
  certManager:
    ##
    ## If preset enables certificate generation via cert-manager namespace scoped issuer
    ##
    issuer: ""
    ##
    ## If preset enables certificate generation via cert-manager cluster-wide issuer
    ##
    clusterIssuer: ""

  ##
  ## Additional ingress annotations to add
  ##
  annotations: {}

  ##
  ## The hostname to be used to precisely map incoming traffic onto the underlying network service
  ##
  hostname: "traceability.local"

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
#   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
