apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: ExternalName
  externalName: {{ .Values.apiService.externalName }}
  ports:
  - name: https
    port: 443
    targetPort: 443
  - name: http
    port: 80
    targetPort: 80
