name: "Dependencies Backend Update"

on:
  push:
    branches:
      - chore/TRACEFOSS-1336-dependencies-github-action

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn org.eclipse.dash:license-tool-plugin:license-check -Ddash.summary=DEPENDENCIES_BACKEND

      - name: Check if file was changed
        run: |
          if git diff --name-only ${{ github.base_ref }}...${{ github.sha }} | grep -q '^DEPENDENCIES_BACKEND$'; then
            echo "The file was changed"
            echo "was_file_changed=true" >> "$GITHUB_ENV"
            git
          else
            echo "The file was not changed"
            echo "was_file_changed=true" >> "$GITHUB_ENV"
          fi

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        if: ${{ env.was_file_changed }} == 'true'

      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          add-paths: |
            DEPENDENCIES_BACKEND
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: action/dependencies
#          base: ${{ github.ref }}
          commit-message: Update Dependencies Backend Action
          title: Update Dependencies Backend
          body: |
            Updates Dependencies
          labels: feature, enhancement
        if: ${{ env.was_file_changed }} == 'true'
