name: graflhelm

on:
  workflow_dispatch:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  helm0:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: get tags
        id: get_tags
        run: |
          git tag

      - name: git tags by pattern
        id: git_tags_by_pattern
        run: |
          git tag | grep -e "^[0-9]*.[0-9]*.[0-9]*$" | tail -1
