name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache jest test report
      id: cache-jest-test-report
      uses: actions/cache@v3
      with:
        path: ./src/tests
        key: ${{ runner.os }}-jest-test-report
    - uses: Borales/actions-yarn@v3.0.0
      with:
        cmd: install # will run `yarn install` command
    - uses: Borales/actions-yarn@v3.0.0
      with:
        cmd: test:ci # will run `yarn test` command
    - uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
